// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADvbeKURwk9-tTXZD2eP-y7ulZV2wh2O4',
    appId: '1:17077142592:android:0493ddcc9da0fe71170ba5',
    messagingSenderId: '17077142592',
    projectId: 'vetp-9624a',
    storageBucket: 'vetp-9624a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmGM5EycnIAUwfmKQAov-xXEAlC6QIVkA',
    appId: '1:17077142592:ios:c3bb8699505271b2170ba5',
    messagingSenderId: '17077142592',
    projectId: 'vetp-9624a',
    storageBucket: 'vetp-9624a.firebasestorage.app',
    iosBundleId: 'com.example.vetpro',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiQtl4lut9-wpWTklmWvIqAFzx24QziKE',
    appId: '1:17077142592:web:1b6def45c0ff2532170ba5',
    messagingSenderId: '17077142592',
    projectId: 'vetp-9624a',
    authDomain: 'vetp-9624a.firebaseapp.com',
    storageBucket: 'vetp-9624a.firebasestorage.app',
    measurementId: 'G-DG94DB5R03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmGM5EycnIAUwfmKQAov-xXEAlC6QIVkA',
    appId: '1:17077142592:ios:c3bb8699505271b2170ba5',
    messagingSenderId: '17077142592',
    projectId: 'vetp-9624a',
    storageBucket: 'vetp-9624a.firebasestorage.app',
    iosBundleId: 'com.example.vetpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiQtl4lut9-wpWTklmWvIqAFzx24QziKE',
    appId: '1:17077142592:web:81990d3105af5983170ba5',
    messagingSenderId: '17077142592',
    projectId: 'vetp-9624a',
    authDomain: 'vetp-9624a.firebaseapp.com',
    storageBucket: 'vetp-9624a.firebasestorage.app',
    measurementId: 'G-S9NMKF1K8G',
  );

}